name = "scrap"
compatibility_date = "2024-10-21"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "scrap_prod"
database_id = "5c11a0e5-3460-480c-bb5c-0971dd645f47"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"