name = "scrap"
compatibility_date = "2024-10-21"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "SESSION_KV"
id = "c05d577e52254456931cef1e83fb0cf4"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "scrap_prod"
database_id = "5c11a0e5-3460-480c-bb5c-0971dd645f47"
migrations_dir = "drizzle"
